### ISSUE TITLE
Articles for Developers

### ISSUE THREAD

**Issue by danielma** [planningcenter/planningcenter.design#13]
:wave: @sheck and I started a conversation today about a developers knowledge base, and felt like the concept is very similar to this project.

I don't know for sure if we should add articles here or start a separate one, but for now, here's a list of developer focused knowledge base articles I'd like to see

## Getting started

- Initial setup (links to pco-box, jamf, viscocity, etc)
- The PC architecture for devs (ACI, databases, elasticsearch, pco-api)
- additional tools (circleci, graylog, bugsnag, migration tool)

## Day to Day

- common `pco-` commands
- shared databases between staging/production
- understanding the read slave

## FAQ

- Questions/answers that get brought up in platform/dev
- How to write no downtime migrations (removing & renaming columns)

**Comment by chantastic** [comment]
awesome! thanks for looping me in.

this list doesn't seem too developer-centric to me.
in fact, a couple of those were on my platform list.

how would you like to proceed?

**Comment by chantastic** [comment]
sounds great to me.

we have a `platform` category now.
let's start by categorizing all as `platform` and see how it feels.

**Comment by danielma** [comment]
I'm so sorry for the false alarm, but we're looking at heading in a different direction.

I just had another conversation with Nick and James, and two major points were brought up.

1. This repo is public, and a big part of our welcome/guide documents will discuss private details
2. We're looking into starting a system of letting devs/designers/anyone open an issue for discussion, which will be better managed in a private internal repo.

Again, sorry for the changing ideas. We've been bouncing things around a bunch and trying to get buy-in, and the goal-posts are changing (in a good way)

**Comment by chantastic** [comment]
For posterity. It's worth reinforcing that both of these can be solved by making the `@planningcenter/planningcenter.design` repo private. And that a developer-specific resource felt valuable for other response that were not solely security oriented.
